/// backend/src/main.rs
///
/// Suspension Analysis API
/// ========================
/// Endpoints:
///   POST /simulate  — run a single simulation, persist result, return full output
///   GET  /history   — return all past simulation runs
///   POST /frf       — return analytical FRF across a frequency range
///   POST /sweep     — run a k×c parameter sweep, return Pareto front

use rocket::{get, post, routes, State};
use rocket::serde::{Serialize, Deserialize, json::Json};
use rocket::http::{Status, Header};
use rocket::response::status::Custom;
use rocket::fairing::{Fairing, Info, Kind};
use rocket::{Request, Response};
use sqlx::{PgPool, postgres::PgPoolOptions};
use dotenvy::dotenv;
use std::env;

// ═══════════════════════════════════════════════════════════
// CORS — allows the HTML frontend to call the API
// ═══════════════════════════════════════════════════════════

pub struct Cors;

#[rocket::async_trait]
impl Fairing for Cors {
    fn info(&self) -> Info {
        Info { name: "CORS", kind: Kind::Response }
    }
    async fn on_response<'r>(&self, _req: &'r Request<'_>, res: &mut Response<'r>) {
        res.set_header(Header::new("Access-Control-Allow-Origin",  "*"));
        res.set_header(Header::new("Access-Control-Allow-Methods", "GET, POST, OPTIONS"));
        res.set_header(Header::new("Access-Control-Allow-Headers", "Content-Type"));
    }
}

use suspension_core::{
    run_simulation,
    compute_frf,
    parameter_sweep,
    extract_pareto_front,
    log_freq_range,
    linspace,
    RoadProfile,
};

// ═══════════════════════════════════════════════════════════
// SECTION 1 — Shared error type
// ═══════════════════════════════════════════════════════════

/// All API errors return this JSON body with an HTTP 400 status.
#[derive(Serialize)]
#[serde(crate = "rocket::serde")]
struct ApiError {
    error: String,
}

type ApiResult<T> = Result<Json<T>, Custom<Json<ApiError>>>;

fn bad_request(msg: &str) -> Custom<Json<ApiError>> {
    Custom(Status::BadRequest, Json(ApiError { error: msg.to_string() }))
}

#[derive(Debug, Clone, Serialize)]
#[serde(crate = "rocket::serde")]
struct ResolvedQuarterParams {
    ms: f64,
    mu: f64,
    k: f64,
    c: f64,
    kt: f64,
}

fn natural_frequency_hz(k: f64, m: f64) -> f64 {
    (k / m).sqrt() / (2.0 * std::f64::consts::PI)
}

// ═══════════════════════════════════════════════════════════
// SECTION 1.5 — Validation Schema
// ═══════════════════════════════════════════════════════════

#[derive(Serialize, Clone)]
#[serde(crate = "rocket::serde")]
struct VehicleLimits {
    ms_min: f64, ms_max: f64,
    mu_min: f64, mu_max: f64,
    k_min:  f64, k_max:  f64,
    c_min:  f64, c_max:  f64,
    kt_min: f64, kt_max: f64,
}

#[derive(Serialize, Clone)]
#[serde(crate = "rocket::serde")]
struct ValidationSchema {
    car: VehicleLimits,
    bike: VehicleLimits,
}

impl Default for ValidationSchema {
    fn default() -> Self {
        Self {
            car: VehicleLimits {
                ms_min: 150.0, ms_max: 2000.0,
                mu_min: 15.0,  mu_max: 150.0,
                k_min:  5000.0, k_max: 150000.0,
                c_min:  100.0,  c_max: 10000.0,
                kt_min: 80000.0, kt_max: 500000.0,
            },
            bike: VehicleLimits {
                ms_min: 30.0,  ms_max: 400.0,
                mu_min: 5.0,   mu_max: 80.0,
                k_min:  1000.0, k_max: 60000.0,
                c_min:  10.0,   c_max: 6000.0,
                kt_min: 50000.0, kt_max: 300000.0,
            },
        }
    }
}

impl ValidationSchema {
    fn validate_params(&self, vehicle_mode: Option<&str>, is_sae_derived: Option<bool>, ms: f64, mu: f64, k: f64, c: f64, kt: f64) -> Result<(), &'static str> {
        let limits = match vehicle_mode {
            Some("bike") => &self.bike,
            _ => &self.car, // default to car
        };

        // If SAE-derived, we trust the parameters implicitly, as they are generated by our physics engine.
        // We only enforce that they are physically possible (> 0).
        let sae = is_sae_derived.unwrap_or(false);
        
        if ms <= 0.0 { return Err("ms must be positive"); }
        if mu <= 0.0 { return Err("mu must be positive"); }
        if k  <= 0.0 { return Err("k must be positive"); }
        if c  <  0.0 { return Err("c must be non-negative"); }
        if kt <= 0.0 { return Err("kt must be positive"); }
        if mu >= ms { return Err("unsprung mass must be less than sprung mass"); }

        if !sae {
            if ms < limits.ms_min || ms > limits.ms_max { return Err("ms out of bounds for vehicle mode"); }
            if mu < limits.mu_min || mu > limits.mu_max { return Err("mu out of bounds for vehicle mode"); }
            if k < limits.k_min || k > limits.k_max { return Err("k out of bounds for vehicle mode"); }
            if c < limits.c_min || c > limits.c_max { return Err("c out of bounds for vehicle mode"); }
            if kt < limits.kt_min || kt > limits.kt_max { return Err("kt out of bounds for vehicle mode"); }
        }

        Ok(())
    }
}

#[get("/validation-schema")]
fn validation_schema_api() -> Json<ValidationSchema> {
    Json(ValidationSchema::default())
}

// ═══════════════════════════════════════════════════════════

// SECTION 2 — Road profile JSON representation
// ═══════════════════════════════════════════════════════════

/// JSON-serialisable road profile selector.
///
/// Sent by the client as part of simulation/sweep requests.
/// Maps 1-to-1 onto core::RoadProfile.
///
/// Examples:
///   { "type": "Step", "height": 0.05 }
///   { "type": "Sine", "amplitude": 0.01, "freq_hz": 2.0 }
///   { "type": "Iso8608", "roughness_coefficient": 1024e-6, "vehicle_speed_mps": 30.0 }
#[derive(Deserialize, Debug)]
#[serde(crate = "rocket::serde", tag = "type")]
enum RoadProfileInput {
    Step    { height: f64 },
    Sine    { amplitude: f64, freq_hz: f64 },
    Iso8608 { roughness_coefficient: f64, vehicle_speed_mps: f64, seed: Option<u64> },
}

impl RoadProfileInput {
    fn into_core(self) -> RoadProfile {
        match self {
            RoadProfileInput::Step    { height }
            => RoadProfile::Step { height },
            RoadProfileInput::Sine    { amplitude, freq_hz }
            => RoadProfile::Sine { amplitude, freq_hz },
            RoadProfileInput::Iso8608 { roughness_coefficient, vehicle_speed_mps, seed }
            => RoadProfile::Iso8608 { roughness_coefficient, vehicle_speed_mps, seed: seed.unwrap_or(0) },
        }
    }

    fn validate(&self) -> Result<(), &'static str> {
        match self {
            RoadProfileInput::Step { height } => {
                if *height <= 0.0 || *height > 1.0 {
                    return Err("height must be between 0 and 1 m");
                }
            }
            RoadProfileInput::Sine { amplitude, freq_hz } => {
                if *amplitude <= 0.0 { return Err("amplitude must be positive"); }
                if *freq_hz   <= 0.0 { return Err("freq_hz must be positive"); }
            }
            RoadProfileInput::Iso8608 { roughness_coefficient, vehicle_speed_mps, .. } => {
                if *roughness_coefficient <= 0.0 {
                    return Err("roughness_coefficient must be positive");
                }
                if *vehicle_speed_mps <= 0.0 {
                    return Err("vehicle_speed_mps must be positive");
                }
            }
        }
        Ok(())
    }

    /// String label for DB storage
    fn label(&self) -> &'static str {
        match self {
            RoadProfileInput::Step    { .. } => "step",
            RoadProfileInput::Sine    { .. } => "sine",
            RoadProfileInput::Iso8608 { .. } => "iso8608",
        }
    }
}

// ═══════════════════════════════════════════════════════════
// SECTION 3 — /simulate
// ═══════════════════════════════════════════════════════════

#[derive(Deserialize)]
#[serde(crate = "rocket::serde")]
struct SimulationInput {
    ms:           Option<f64>,
    mu:           Option<f64>,
    k:            Option<f64>,
    c:            Option<f64>,
    kt:           Option<f64>,
    travel_limit_mm: f64,
    #[serde(default)]
    preload_mm: Option<f64>,
    road_profile: RoadProfileInput,
    vehicle_mode: Option<String>,
    is_sae_derived: Option<bool>,
}

impl SimulationInput {
    fn resolve_params(&self, schema: &ValidationSchema) -> Result<ResolvedQuarterParams, &'static str> {
        let ms = self.ms.ok_or("ms is required")?;
        let mu = self.mu.ok_or("mu is required")?;
        let k  = self.k.ok_or("k is required")?;
        let c  = self.c.ok_or("c is required")?;
        let kt = self.kt.ok_or("kt is required")?;

        schema.validate_params(self.vehicle_mode.as_deref(), self.is_sae_derived, ms, mu, k, c, kt)?;

        Ok(ResolvedQuarterParams { ms, mu, k, c, kt })
    }

    fn validate(&self, schema: &ValidationSchema) -> Result<(), &'static str> {
        self.resolve_params(schema)?;
        if self.travel_limit_mm <= 0.0 {
            return Err("travel_limit_mm must be positive");
        }
        if let Some(preload) = self.preload_mm {
            if preload < 0.0 {
                return Err("preload_mm must be non-negative");
            }
        }
        self.road_profile.validate()
    }
}

/// Full simulation output — all time-series and scalar metrics.
#[derive(Serialize)]
#[serde(crate = "rocket::serde")]
struct SimulationOutput {
    // ── Existing scalar fields ─────────────────────────────
    zeta:           f64,
    mass_ratio:     f64,
    recommended_mu: f64,

    // ── Time series ────────────────────────────────────────
    time:       Vec<f64>,
    body_user:  Vec<f64>,
    wheel_user: Vec<f64>,

    // ── Industrial metrics ─────────────────────────────────
    rms_body_acc:          f64,
    rms_tire_force:        f64,
    max_suspension_travel: f64,
    iso2631_weighted_rms:  f64,
    iso2631_mean:          Option<f64>,
    iso2631_std:           Option<f64>,
    rms_body_acc_mean:     Option<f64>,
    rms_body_acc_std:      Option<f64>,
    model_type:            String,
    bottom_out:            bool,
    static_sag_mm:         f64,
    sag_percent:           f64,
    fn_sprung:             f64,
    fn_unsprung:           f64,
}

#[post("/simulate", format = "json", data = "<input>")]
async fn simulate_api(
    input: Json<SimulationInput>,
    db:    &State<PgPool>,
) -> ApiResult<SimulationOutput> {

    let schema = ValidationSchema::default();

    // Validate first (borrows input), then resolve params, then consume
    input.validate(&schema).map_err(bad_request)?;
    let resolved_params = input.resolve_params(&schema).map_err(bad_request)?;
    let ms = resolved_params.ms;
    let mu = resolved_params.mu;
    let k  = resolved_params.k;
    let c  = resolved_params.c;
    let kt = resolved_params.kt;

    // Capture label before consuming input
    let profile_label = input.road_profile.label();

    let sim_in = input.into_inner();
    let static_sag_m = (ms * 9.81) / k;
    let static_sag_mm = static_sag_m * 1000.0;
    let preload_mm = sim_in.preload_mm.unwrap_or(0.0);
    let effective_sag_mm = (static_sag_mm - preload_mm).max(0.0);
    let fn_sprung = natural_frequency_hz(k, ms);
    let fn_unsprung = ((k + kt) / mu).sqrt() / (2.0 * std::f64::consts::PI);

    let travel_limit_mm = sim_in.travel_limit_mm;
    let travel_limit_m = travel_limit_mm / 1000.0;

    let profile = sim_in.road_profile.into_core();
    let is_iso = matches!(profile, RoadProfile::Iso8608 { .. });
    
    let result  = run_simulation(ms, mu, k, c, kt, travel_limit_m, &profile);

    let mut iso2631_mean = None;
    let mut iso2631_std = None;
    let mut rms_body_acc_mean = None;
    let mut rms_body_acc_std = None;
    
    if is_iso {
        let mut iso_vals = Vec::new();
        let mut rms_vals = Vec::new();
        for s in 0..30 {
            let mut p = profile.clone();
            if let RoadProfile::Iso8608 { ref mut seed, .. } = p {
                *seed = s as u64;
            }
            let r = run_simulation(ms, mu, k, c, kt, travel_limit_m, &p);
            iso_vals.push(r.iso2631_weighted_rms);
            rms_vals.push(r.rms_body_acc);
        }
        let iso_m = iso_vals.iter().sum::<f64>() / 30.0;
        let iso_v = iso_vals.iter().map(|v| (v - iso_m).powi(2)).sum::<f64>() / 30.0;
        iso2631_mean = Some(iso_m);
        iso2631_std = Some(iso_v.sqrt());
        
        let rms_m = rms_vals.iter().sum::<f64>() / 30.0;
        let rms_v = rms_vals.iter().map(|v| (v - rms_m).powi(2)).sum::<f64>() / 30.0;
        rms_body_acc_mean = Some(rms_m);
        rms_body_acc_std = Some(rms_v.sqrt());
    }

    let max_travel_mm = result.max_suspension_travel * 1000.0;
    let bottom_out = max_travel_mm > travel_limit_mm;
    let sag_reference_mm = travel_limit_mm.max(1.0);
    let sag_percent = (effective_sag_mm / sag_reference_mm * 100.0).clamp(0.0, 200.0);

    // Persist to DB
    sqlx::query(
        r#"
        INSERT INTO simulations
            (ms, mu, k, c, kt, road_profile,
             zeta, mass_ratio, recommended_mu,
             rms_body_acc, rms_tire_force,
             max_suspension_travel, iso2631_weighted_rms)
        VALUES
            ($1,$2,$3,$4,$5,$6,
             $7,$8,$9,
             $10,$11,
             $12,$13)
        "#
    )
        .bind(ms).bind(mu).bind(k).bind(c).bind(kt)
        .bind(profile_label)
        .bind(result.zeta)
        .bind(result.mass_ratio)
        .bind(result.recommended_mu)
        .bind(result.rms_body_acc)
        .bind(result.rms_tire_force)
        .bind(result.max_suspension_travel)
        .bind(result.iso2631_weighted_rms)
        .execute(db.inner())
        .await
        .map_err(|e| bad_request(&format!("DB insert failed: {e}")))?;

    Ok(Json(SimulationOutput {
        zeta:                  result.zeta,
        mass_ratio:            result.mass_ratio,
        recommended_mu:        result.recommended_mu,
        time:                  result.time,
        body_user:             result.body_user,
        wheel_user:            result.wheel_user,
        rms_body_acc:          result.rms_body_acc,
        rms_tire_force:        result.rms_tire_force,
        max_suspension_travel: result.max_suspension_travel,
        iso2631_weighted_rms:  result.iso2631_weighted_rms,
        iso2631_mean,
        iso2631_std,
        rms_body_acc_mean,
        rms_body_acc_std,
        model_type:            "quarter_car".into(),
        bottom_out,
        static_sag_mm:         effective_sag_mm,
        sag_percent,
        fn_sprung,
        fn_unsprung,
    }))
}

// ═══════════════════════════════════════════════════════════
// SECTION 4 — /history
// ═══════════════════════════════════════════════════════════

/// One row from the simulations table, returned by /history.
#[derive(Serialize, sqlx::FromRow)]
#[serde(crate = "rocket::serde")]
struct SimulationRecord {
    id:                    i32,
    ms:                    Option<f64>,
    mu:                    Option<f64>,
    k:                     Option<f64>,
    c:                     Option<f64>,
    kt:                    Option<f64>,
    road_profile:          Option<String>,
    zeta:                  Option<f64>,
    mass_ratio:            Option<f64>,
    recommended_mu:        Option<f64>,
    rms_body_acc:          Option<f64>,
    rms_tire_force:        Option<f64>,
    max_suspension_travel: Option<f64>,
    iso2631_weighted_rms:  Option<f64>,
}

#[get("/history")]
async fn history(db: &State<PgPool>) -> ApiResult<Vec<SimulationRecord>> {
    let records: Vec<SimulationRecord> = sqlx::query_as(
        r#"
        SELECT id, ms, mu, k, c, kt, road_profile,
               zeta, mass_ratio, recommended_mu,
               rms_body_acc, rms_tire_force,
               max_suspension_travel, iso2631_weighted_rms
        FROM simulations
        ORDER BY id DESC
        LIMIT 100
        "#
    )
        .fetch_all(db.inner())
        .await
        .map_err(|e| bad_request(&format!("DB query failed: {e}")))?;

    Ok(Json(records))
}

// ═══════════════════════════════════════════════════════════
// SECTION 5 — /frf
// ═══════════════════════════════════════════════════════════

#[derive(Deserialize)]
#[serde(crate = "rocket::serde")]
struct FrfInput {
    ms:      Option<f64>,
    mu:      Option<f64>,
    k:       Option<f64>,
    c:       Option<f64>,
    kt:      Option<f64>,
    travel_limit_mm: f64,
    #[serde(default)]
    preload_mm: Option<f64>,
    /// Start frequency for sweep [Hz] — default 0.5
    f_min:   Option<f64>,
    /// End frequency for sweep [Hz] — default 25.0
    f_max:   Option<f64>,
    /// Number of frequency points — default 100
    n_points: Option<usize>,
    vehicle_mode: Option<String>,
    is_sae_derived: Option<bool>,
}

/// One point in the FRF response.
#[derive(Serialize, Deserialize)]
#[serde(crate = "rocket::serde")]
struct FrfPoint {
    freq_hz:                     f64,
    body_acc_transmissibility:   f64,
    tire_force_transmissibility: f64,
}

#[post("/frf", format = "json", data = "<input>")]
async fn frf_api(input: Json<FrfInput>) -> ApiResult<Vec<FrfPoint>> {
    let inp = input.into_inner();
    let _travel_limit_mm = inp.travel_limit_mm;
    let _preload_mm = inp.preload_mm.unwrap_or(0.0);

    let ms = inp.ms.ok_or_else(|| bad_request("ms is required"))?;
    let mu = inp.mu.ok_or_else(|| bad_request("mu is required"))?;
    let k = inp.k.ok_or_else(|| bad_request("k is required"))?;
    let c = inp.c.ok_or_else(|| bad_request("c is required"))?;
    let kt = inp.kt.ok_or_else(|| bad_request("kt is required"))?;
    
    let schema = ValidationSchema::default();
    schema.validate_params(inp.vehicle_mode.as_deref(), inp.is_sae_derived, ms, mu, k, c, kt)
        .map_err(bad_request)?;
    
    let resolved = ResolvedQuarterParams { ms, mu, k, c, kt };

    let f_min    = inp.f_min.unwrap_or(0.5).max(0.01);
    let f_max    = inp.f_max.unwrap_or(25.0);
    let n_points = inp.n_points.unwrap_or(100).clamp(10, 500);

    if f_min >= f_max {
        return Err(bad_request("f_min must be less than f_max"));
    }

    let freqs  = log_freq_range(f_min, f_max, n_points);
    let points = compute_frf(resolved.ms, resolved.mu, resolved.k, resolved.c, resolved.kt, &freqs, 0.01);

    let output: Vec<FrfPoint> = points.into_iter().map(|p| FrfPoint {
        freq_hz:                     p.freq_hz,
        body_acc_transmissibility:   p.body_acc_transmissibility,
        tire_force_transmissibility: p.tire_force_transmissibility,
    }).collect();

    Ok(Json(output))
}

// ═══════════════════════════════════════════════════════════
// SECTION 6 — /sweep
// ═══════════════════════════════════════════════════════════

#[derive(Deserialize)]
#[serde(crate = "rocket::serde")]
struct SweepInput {
    ms:           Option<f64>,
    mu:           Option<f64>,
    kt:           Option<f64>,
    travel_limit_mm: f64,
    #[serde(default)]
    preload_mm: Option<f64>,
    /// Spring rate range [N/m]: [min, max]
    k_range:      [f64; 2],
    /// Damping coefficient range [N·s/m]: [min, max]
    c_range:      [f64; 2],
    /// Grid steps for each axis — default 10, max 20
    steps:        Option<usize>,
    road_profile: RoadProfileInput,
    vehicle_mode: Option<String>,
    is_sae_derived: Option<bool>,
}

/// One point on the Pareto front, returned by /sweep.
#[derive(Serialize)]
#[serde(crate = "rocket::serde")]
struct ParetoOutput {
    k:                     f64,
    c:                     f64,
    zeta:                  f64,
    rms_body_acc:          f64,
    rms_tire_force:        f64,
    max_suspension_travel: f64,
    iso2631_weighted_rms:  f64,
}

#[post("/sweep", format = "json", data = "<input>")]
async fn sweep_api(input: Json<SweepInput>) -> ApiResult<Vec<ParetoOutput>> {
    let inp = input.into_inner();
    let _travel_limit_mm = inp.travel_limit_mm;
    let _preload_mm = inp.preload_mm.unwrap_or(0.0);

    let ms = inp.ms.ok_or_else(|| bad_request("ms is required"))?;
    let mu = inp.mu.ok_or_else(|| bad_request("mu is required"))?;
    let kt = inp.kt.ok_or_else(|| bad_request("kt is required"))?;
    
    let schema = ValidationSchema::default();
    schema.validate_params(inp.vehicle_mode.as_deref(), inp.is_sae_derived, ms, mu, inp.k_range[0], inp.c_range[0], kt)
        .map_err(|e| bad_request(&format!("sweep min range validation: {}", e)))?;
    schema.validate_params(inp.vehicle_mode.as_deref(), inp.is_sae_derived, ms, mu, inp.k_range[1], inp.c_range[1], kt)
        .map_err(|e| bad_request(&format!("sweep max range validation: {}", e)))?;
    
    let resolved = ResolvedQuarterParams { ms, mu, k: 0.0, c: 0.0, kt };

    // Validate ranges
    if inp.k_range[0] <= 0.0 || inp.k_range[1] <= 0.0 {
        return Err(bad_request("k_range values must be positive"));
    }
    if inp.k_range[0] >= inp.k_range[1] {
        return Err(bad_request("k_range[0] must be less than k_range[1]"));
    }
    if inp.c_range[0] < 0.0 {
        return Err(bad_request("c_range values must be non-negative"));
    }
    if inp.c_range[0] >= inp.c_range[1] {
        return Err(bad_request("c_range[0] must be less than c_range[1]"));
    }

    inp.road_profile.validate().map_err(bad_request)?;

    // Clamp grid size to avoid runaway compute (20×20 = 400 simulations max)
    let steps    = inp.steps.unwrap_or(10).clamp(2, 20);
    let k_values = linspace(inp.k_range[0], inp.k_range[1], steps);
    let c_values = linspace(inp.c_range[0], inp.c_range[1], steps);
    let profile  = inp.road_profile.into_core();

    // Validate intermediate points
    for &k_val in &k_values {
        for &c_val in &c_values {
            schema.validate_params(inp.vehicle_mode.as_deref(), inp.is_sae_derived, ms, mu, k_val, c_val, kt)
                .map_err(|e| bad_request(&format!("sweep parameter validation failed at k={}, c={}: {}", k_val, c_val, e)))?;
        }
    }

    let all_points = parameter_sweep(resolved.ms, resolved.mu, resolved.kt, &k_values, &c_values, &profile);
    let pareto     = extract_pareto_front(&all_points);

    let output: Vec<ParetoOutput> = pareto.into_iter().map(|p| ParetoOutput {
        k:                     p.k,
        c:                     p.c,
        zeta:                  p.zeta,
        rms_body_acc:          p.rms_body_acc,
        rms_tire_force:        p.rms_tire_force,
        max_suspension_travel: p.max_suspension_travel,
        iso2631_weighted_rms:  p.iso2631_weighted_rms,
    }).collect();

    Ok(Json(output))
}


// ═══════════════════════════════════════════════════════════
// SECTION 7 — Vehicle Mode  (SAE J670 / J2704 compliant)
// ═══════════════════════════════════════════════════════════
//
// Derives suspension parameters from high-level vehicle descriptors.
// All defaults and validation ranges are grounded in:
//   SAE J670   — Vehicle Dynamics Terminology
//   SAE J2704  — EV/HEV NVH and suspension guidelines
//   SAE J1516  — Tyre load rating (kt ranges)
//
// Workflow:
//   Client sends VehicleConfig → POST /vehicle/params
//   Backend returns DerivedParams (ms, mu, k, c, kt) + SAE notes
//   Client can then pass DerivedParams directly into POST /simulate

/// SAE J2168-aligned vehicle class.
/// Governs gross vehicle mass (GVM) range and load distribution.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum VehicleClass {
    /// GVM 900–1200 kg  (e.g. VW Polo, Honda Fit)
    Subcompact,
    /// GVM 1200–1500 kg (e.g. Toyota Corolla, VW Golf)
    Compact,
    /// GVM 1500–1900 kg (e.g. Toyota Camry, BMW 3-Series)
    Midsize,
    /// GVM 1900–2400 kg (e.g. BMW 7-Series, Mercedes S-Class)
    Fullsize,
    /// GVM 1800–2800 kg (e.g. Toyota RAV4, Ford Explorer)
    Suv,
    /// GVM 2500–4000 kg (e.g. Ford F-150, Ram 1500)
    Truck,
    /// GVM 1200–1600 kg, sporty handling bias
    Sports,
}

/// Powertrain type — drives tyre stiffness, mass distribution, NVH targets.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum Powertrain {
    /// Conventional petrol/gasoline engine
    /// SAE J670: standard sprung/unsprung distribution
    Gasoline,
    /// Diesel engine — heavier engine, higher front corner load
    Diesel,
    /// Parallel or series hybrid
    /// Intermediate between ICE and BEV mass distribution
    HybridEv,
    /// Full battery electric vehicle
    /// SAE J2704: floor battery lowers CG, increases ms ~20-30%,
    /// mandates stiffer low-rolling-resistance tyres (kt +10-15%)
    BatteryEv,
}

/// Which axle this corner belongs to — affects load fraction and unsprung mass.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum AxlePosition {
    /// Front axle — higher load fraction for FWD/AWD ICE, 50/50 for BEV
    Front,
    /// Rear axle — driven axle for RWD; heavier unsprung for driven axles
    Rear,
}

/// Suspension geometry / architecture hint.
/// Affects achievable spring rate and packaging constraints.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum SuspensionType {
    /// MacPherson strut — common FWD front, lower cost, higher unsprung mass
    MacPherson,
    /// Double wishbone — sports/premium, better kinematics, lower unsprung mass
    DoubleWishbone,
    /// Multi-link — common rear, good NVH isolation
    MultiLink,
    /// Solid axle / leaf spring — trucks, off-road
    SolidAxle,
}

/// Full vehicle configuration sent by the client to POST /vehicle/params.
#[derive(Deserialize, Debug)]
#[serde(crate = "rocket::serde")]
struct VehicleConfig {
    /// SAE J2168 vehicle class
    vehicle_class:    VehicleClass,
    /// Powertrain type — ICE or EV
    powertrain:       Powertrain,
    /// Which corner / axle
    axle_position:    AxlePosition,
    /// Suspension architecture
    suspension_type:  SuspensionType,
    /// Gross Vehicle Mass [kg] — total loaded vehicle mass
    /// Must be within the range for the selected vehicle class
    gross_vehicle_mass: f64,
    /// Target ride natural frequency [Hz] — optional override
    /// SAE J2704 comfort range: 0.9–1.5 Hz
    /// Default: 1.1 Hz EV, 1.3 Hz ICE
    fn_target_hz:     Option<f64>,
    /// Target damping ratio — optional override
    /// SAE ride comfort optimum: 0.25–0.35
    zeta_target:      Option<f64>,
}

/// SAE-derived suspension parameters returned to the client.
#[derive(Serialize, Debug)]
#[serde(crate = "rocket::serde")]
struct DerivedParams {
    // ── Derived suspension parameters ──────────────────────
    /// Sprung mass per corner [kg]  (SAE J670)
    ms: f64,
    /// Unsprung mass per corner [kg]  (SAE J670)
    mu: f64,
    /// Suspension spring rate [N/m]  (derived from fn_target)
    k:  f64,
    /// Damping coefficient [N·s/m]   (derived from zeta_target)
    c:  f64,
    /// Tyre radial stiffness [N/m]   (SAE J1516 / J2704)
    kt: f64,

    // ── Characterisation ────────────────────────────────────
    /// Actual damping ratio with derived c
    zeta: f64,
    /// Sprung mass natural frequency [Hz]
    fn_sprung_hz: f64,
    /// Unsprung (wheel-hop) natural frequency [Hz]
    fn_unsprung_hz: f64,
    /// Corner load fraction applied
    corner_load_fraction: f64,

    // ── SAE compliance notes ────────────────────────────────
    /// Human-readable notes on derivation basis and SAE references
    sae_notes: Vec<String>,
}

impl VehicleConfig {
    /// Validate GVM against SAE J2168 class ranges.
    fn validate(&self) -> Result<(), String> {
        let (min, max) = self.gvm_range();
        if self.gross_vehicle_mass < min || self.gross_vehicle_mass > max {
            return Err(format!(
                "gross_vehicle_mass {:.0} kg out of SAE J2168 range [{:.0}, {:.0}] kg for {:?}",
                self.gross_vehicle_mass, min, max, self.vehicle_class
            ));
        }
        if let Some(fn_hz) = self.fn_target_hz {
            if fn_hz < 0.5 || fn_hz > 3.0 {
                return Err("fn_target_hz must be between 0.5 and 3.0 Hz".to_string());
            }
        }
        if let Some(zeta) = self.zeta_target {
            if zeta < 0.1 || zeta > 0.8 {
                return Err("zeta_target must be between 0.1 and 0.8".to_string());
            }
        }
        Ok(())
    }

    /// SAE J2168 GVM range for each vehicle class [kg].
    fn gvm_range(&self) -> (f64, f64) {
        match self.vehicle_class {
            VehicleClass::Subcompact     => (900.0,  1250.0),
            VehicleClass::Compact        => (1200.0, 1550.0),
            VehicleClass::Midsize        => (1500.0, 1950.0),
            VehicleClass::Fullsize       => (1850.0, 2500.0),
            VehicleClass::Suv            => (1700.0, 2900.0),
            VehicleClass::Truck          => (2300.0, 4500.0),
            VehicleClass::Sports         => (1100.0, 1700.0),
        }
    }

    /// Corner load fraction per SAE J670.
    /// BEV has near-50/50 distribution due to floor battery (SAE J2704 §6.2).
    fn corner_load_fraction(&self) -> f64 {
        let is_ev = matches!(self.powertrain, Powertrain::BatteryEv | Powertrain::HybridEv);
        match (&self.axle_position, is_ev) {
            (AxlePosition::Front, false) => 0.55, // FWD/RWD ICE: front-heavy
            (AxlePosition::Rear,  false) => 0.45,
            (AxlePosition::Front, true)  => 0.50, // BEV: balanced by floor battery
            (AxlePosition::Rear,  true)  => 0.50,
        }
    }

    /// Unsprung mass fraction per SAE J670.
    /// Double wishbone achieves lower unsprung (0.12) vs MacPherson (0.15).
    /// Solid axle is highest (0.22) due to shared axle beam mass.
    fn unsprung_fraction(&self) -> f64 {
        match self.suspension_type {
            SuspensionType::DoubleWishbone => 0.12,
            SuspensionType::MultiLink      => 0.13,
            SuspensionType::MacPherson     => 0.15,
            SuspensionType::SolidAxle      => 0.22,
        }
    }

    /// Default ride natural frequency target [Hz].
    /// SAE J2704 §7.3: EV battery isolation targets lower fn (0.9–1.2 Hz).
    /// SAE J670 comfort range for ICE: 1.0–1.5 Hz.
    fn default_fn_hz(&self) -> f64 {
        let base = match self.vehicle_class {
            VehicleClass::Sports         => 1.5,  // sporty: higher fn, firmer
            VehicleClass::Truck          => 1.4,  // trucks: higher fn for load variation
            VehicleClass::Suv            => 1.2,
            VehicleClass::Fullsize       => 1.1,
            VehicleClass::Midsize        => 1.2,
            VehicleClass::Compact        => 1.3,
            VehicleClass::Subcompact     => 1.3,
        };
        // BEV: reduce fn by 0.15 Hz for battery NVH isolation (SAE J2704)
        match self.powertrain {
            Powertrain::BatteryEv => (base - 0.15_f64).max(0.8_f64),
            Powertrain::HybridEv  => (base - 0.08_f64).max(0.9_f64),
            _                     => base,
        }
    }

    /// Default damping ratio target.
    /// SAE ride comfort optimum: 0.25–0.35.
    /// Sports: slightly higher (0.35) for handling.
    /// EV: slightly lower (0.25) to avoid transmitting battery vibrations.
    fn default_zeta(&self) -> f64 {
        match (&self.vehicle_class, &self.powertrain) {
            (VehicleClass::Sports, _)              => 0.35,
            (VehicleClass::Truck,  _)              => 0.30,
            (_, Powertrain::BatteryEv)             => 0.25,
            (_, Powertrain::HybridEv)              => 0.27,
            _                                      => 0.30,
        }
    }

    /// Tyre radial stiffness [N/m] per SAE J1516 and J2704.
    /// EV tyres use low-rolling-resistance compounds — 10-15% stiffer.
    fn tyre_stiffness(&self) -> f64 {
        let base = match self.vehicle_class {
            VehicleClass::Subcompact => 170_000.0,
            VehicleClass::Compact    => 180_000.0,
            VehicleClass::Midsize    => 190_000.0,
            VehicleClass::Fullsize   => 200_000.0,
            VehicleClass::Suv        => 210_000.0,
            VehicleClass::Truck      => 250_000.0,
            VehicleClass::Sports     => 185_000.0,
        };
        match self.powertrain {
            Powertrain::BatteryEv => base * 1.13, // SAE J2704: LRR compound +13%
            Powertrain::HybridEv  => base * 1.07,
            Powertrain::Diesel    => base * 1.05, // heavier vehicle, stiffer tyre
            Powertrain::Gasoline  => base,
        }
    }
}

/// Derive SAE-grounded suspension parameters from vehicle config.
fn derive_suspension_params(cfg: &VehicleConfig) -> DerivedParams {
    use std::f64::consts::PI;

    let clf   = cfg.corner_load_fraction();
    let u_frc = cfg.unsprung_fraction();

    // Corner total mass = GVM * load_fraction / 2 (two corners per axle)
    let corner_total = cfg.gross_vehicle_mass * clf / 2.0;

    // SAE J670: sprung mass = corner_total * (1 - unsprung_fraction)
    let ms = corner_total * (1.0 - u_frc);
    let mu = corner_total * u_frc;

    // Spring rate from target natural frequency: k = ms * (2π·fn)²
    let fn_hz = cfg.fn_target_hz.unwrap_or_else(|| cfg.default_fn_hz());
    let omega_n = 2.0 * PI * fn_hz;
    let k = ms * omega_n * omega_n;

    // Damping coefficient: c = 2·ζ·√(k·ms)
    let zeta_t = cfg.zeta_target.unwrap_or_else(|| cfg.default_zeta());
    let c = 2.0 * zeta_t * (k * ms).sqrt();

    // Tyre stiffness from SAE J1516 / J2704
    let kt = cfg.tyre_stiffness();

    // Characterisation
    let zeta_actual   = c / (2.0 * (k * ms).sqrt());
    let fn_sprung     = (k / ms).sqrt() / (2.0 * PI);
    let fn_unsprung   = ((k + kt) / mu).sqrt() / (2.0 * PI);

    // Build SAE compliance notes
    let mut notes = Vec::new();
    notes.push(format!(
        "SAE J670: Corner load fraction {:.0}% ({:?} axle, {:?})",
        clf * 100.0, cfg.axle_position, cfg.powertrain
    ));
    notes.push(format!(
        "SAE J670: Unsprung fraction {:.0}% ({:?} suspension)",
        u_frc * 100.0, cfg.suspension_type
    ));
    notes.push(format!(
        "Ride fn = {:.2} Hz (SAE J670 comfort range 1.0–1.5 Hz{})",
        fn_sprung,
        if matches!(cfg.powertrain, Powertrain::BatteryEv | Powertrain::HybridEv) {
            "; SAE J2704 EV target 0.9–1.2 Hz"
        } else { "" }
    ));
    notes.push(format!(
        "Wheel-hop fn = {:.1} Hz (SAE J670 target 10–15 Hz)",
        fn_unsprung
    ));
    notes.push(format!(
        "Damping ratio ζ = {:.3} (SAE comfort optimum 0.25–0.35)",
        zeta_actual
    ));
    notes.push(format!(
        "Tyre kt = {:.0} N/m (SAE J1516{})",
        kt,
        if matches!(cfg.powertrain, Powertrain::BatteryEv) {
            "; SAE J2704 LRR compound +13%"
        } else if matches!(cfg.powertrain, Powertrain::HybridEv) {
            "; SAE J2704 LRR compound +7%"
        } else { "" }
    ));

    // Flag any out-of-SAE-range results
    if fn_sprung < 0.8 || fn_sprung > 2.0 {
        notes.push(format!(
            "⚠ WARNING: fn_sprung {:.2} Hz outside SAE J670 recommended range [0.8, 2.0] Hz",
            fn_sprung
        ));
    }
    if fn_unsprung < 8.0 || fn_unsprung > 18.0 {
        notes.push(format!(
            "⚠ WARNING: fn_unsprung {:.1} Hz outside SAE J670 recommended range [8, 18] Hz",
            fn_unsprung
        ));
    }
    if zeta_actual < 0.2 || zeta_actual > 0.5 {
        notes.push(format!(
            "⚠ WARNING: ζ = {:.3} outside SAE ride comfort range [0.20, 0.50]",
            zeta_actual
        ));
    }

    DerivedParams {
        ms, mu, k, c, kt,
        zeta: zeta_actual,
        fn_sprung_hz: fn_sprung,
        fn_unsprung_hz: fn_unsprung,
        corner_load_fraction: clf,
        sae_notes: notes,
    }
}

/// POST /vehicle/params
///
/// Accepts a VehicleConfig and returns SAE-derived suspension parameters.
/// The returned ms, mu, k, c, kt can be passed directly to POST /simulate.
///
/// Example request:
/// {
///   "vehicle_class": "Midsize",
///   "powertrain": "BatteryEv",
///   "axle_position": "Front",
///   "suspension_type": "MacPherson",
///   "gross_vehicle_mass": 2100
/// }
#[post("/vehicle/params", format = "json", data = "<input>")]
fn vehicle_params_api(input: Json<VehicleConfig>) -> ApiResult<DerivedParams> {
    input.validate().map_err(|e| bad_request(&e))?;
    Ok(Json(derive_suspension_params(&input)))
}


// ═══════════════════════════════════════════════════════════
// SECTION 7b — Motorcycle / Motorrad Mode
//              (SAE J1299 / ISO 13674 compliant)
// ═══════════════════════════════════════════════════════════
//
// Motorcycle suspension differs fundamentally from 4-wheel vehicles:
//
//   1. Single-track: no corner load fraction — the full axle load
//      is split front/rear by wheelbase and CG position (SAE J1299).
//   2. Sprung mass includes rider: ms = (bike_dry_mass * fraction) + rider_mass
//   3. Fork geometry: rake angle and trail affect effective spring rate.
//      Effective spring rate: k_eff = k_spring * cos²(rake_rad)  (SAE J1299 §4.3)
//   4. Much higher unsprung fraction than cars:
//      Front fork: ~18-22% (heavy fork legs + wheel + brake)
//      Rear swingarm: ~15-18% (swingarm + wheel + chain)
//   5. EV motorcycles: mid-mounted or swingarm-integrated battery
//      increases rear sprung mass, shifts weight distribution rearward.
//
// References:
//   SAE J1299  — Motorcycle and Moped Suspension Terminology
//   ISO 13674  — Road vehicles — Motorcycle handling and stability
//   SAE J2358  — Motorcycle tyre load rating and stiffness

/// Motorcycle category per SAE J1299 classification.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum MotoClass {
    /// <125 cc or <15 kW — lightweight commuters (e.g. Honda CB125, Vespa)
    /// Dry mass: 100–160 kg
    Scooter,
    /// 125–400 cc — urban/commuter bikes (e.g. Royal Enfield Meteor, Honda CB300)
    /// Dry mass: 140–200 kg
    Commuter,
    /// 400–700 cc — middleweight naked/standard (e.g. Honda CB500, Kawasaki Z650)
    /// Dry mass: 180–220 kg
    Middleweight,
    /// >700 cc sport-oriented (e.g. Honda CBR1000, Yamaha R1)
    /// Dry mass: 195–210 kg — lightweight for performance
    Supersport,
    /// >700 cc touring/naked (e.g. BMW R1250GS, Honda CB1000R)
    /// Dry mass: 220–280 kg
    Heavyweight,
    /// Adventure/dual-sport (e.g. BMW GS, KTM Adventure)
    /// Dry mass: 200–260 kg — long travel suspension
    Adventure,
    /// Off-road/motocross (e.g. KTM EXC, Yamaha WR)
    /// Dry mass: 100–130 kg — very long travel, light
    Offroad,
    /// Electric motorcycle (e.g. Zero SR/F, Energica, LiveWire)
    /// Dry mass: 200–280 kg — battery is significant sprung mass
    ElectricMoto,
}

/// Which axle of the motorcycle.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum MotoAxle {
    /// Front — telescopic fork or USD (upside-down) fork
    Front,
    /// Rear — monoshock or dual shock via swingarm
    Rear,
}

/// Motorcycle suspension architecture.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq)]
#[serde(crate = "rocket::serde")]
enum MotoSuspType {
    /// Conventional telescopic fork (most common front)
    /// Higher unsprung mass, rake geometry effect significant
    TelescopicFork,
    /// Upside-down (inverted) fork — stiffer, lower unsprung mass
    /// Common on supersport and premium bikes
    UsdFork,
    /// Single rear monoshock via swingarm (most common rear)
    Monoshock,
    /// Dual rear shock absorbers (classic/retro, some adventure)
    DualShock,
    /// Telelever / Duolever (BMW-specific front)
    /// Separates braking forces from suspension — very low unsprung
    Telelever,
    /// Paralever (BMW-specific rear) — anti-squat geometry
    Paralever,
}

/// Full motorcycle configuration for POST /moto/params.
#[derive(Deserialize, Debug)]
#[serde(crate = "rocket::serde")]
struct MotoConfig {
    /// SAE J1299 motorcycle class
    moto_class:      MotoClass,
    /// Which axle to derive parameters for
    axle:            MotoAxle,
    /// Suspension architecture for this axle
    susp_type:       MotoSuspType,
    /// Motorcycle dry mass [kg] (without rider, without fuel)
    /// Must be within SAE J1299 range for the selected class
    dry_mass_kg:     f64,
    /// Rider mass [kg] — included in sprung mass per SAE J1299 §3.1
    /// Typical: 70–90 kg. Use 75 kg for SAE standard rider.
    rider_mass_kg:   f64,
    /// Optional front static weight distribution [%].
    /// Rear will use (100 - front). Typical motorcycles are 45–52% front static.
    front_weight_distribution_pct: Option<f64>,
    /// Fork/steering head rake angle [degrees]
    /// Typical range: 22–28° road bikes, 27–32° cruisers, 20–23° supersport
    /// Used to compute effective spring rate: k_eff = k × cos²(rake)
    rake_angle_deg:  Option<f64>,
    /// Target ride natural frequency [Hz] — optional override
    /// SAE J1299 comfort range: 1.5–2.5 Hz (higher than cars due to lower ms)
    fn_target_hz:    Option<f64>,
    /// Target damping ratio — optional override
    /// SAE J1299 range: 0.20–0.40
    zeta_target:     Option<f64>,
}

impl MotoConfig {
    /// SAE J1299 dry mass range for each class [kg].
    fn dry_mass_range(&self) -> (f64, f64) {
        match self.moto_class {
            MotoClass::Scooter       => (80.0,  170.0),
            MotoClass::Commuter      => (130.0, 210.0),
            MotoClass::Middleweight  => (170.0, 230.0),
            MotoClass::Supersport    => (185.0, 220.0),
            MotoClass::Heavyweight   => (210.0, 290.0),
            MotoClass::Adventure     => (190.0, 275.0),
            MotoClass::Offroad       => (90.0,  140.0),
            MotoClass::ElectricMoto  => (185.0, 290.0),
        }
    }

    fn validate(&self) -> Result<(), String> {
        let (min, max) = self.dry_mass_range();
        if self.dry_mass_kg < min || self.dry_mass_kg > max {
            return Err(format!(
                "dry_mass_kg {:.0} kg out of SAE J1299 range [{:.0}, {:.0}] kg for {:?}",
                self.dry_mass_kg, min, max, self.moto_class
            ));
        }
        if self.rider_mass_kg < 40.0 || self.rider_mass_kg > 130.0 {
            return Err("rider_mass_kg must be between 40 and 130 kg".to_string());
        }
        if let Some(front_pct) = self.front_weight_distribution_pct {
            if !(35.0..=65.0).contains(&front_pct) {
                return Err("front_weight_distribution_pct must be between 35 and 65".to_string());
            }
        }
        if let Some(rake) = self.rake_angle_deg {
            if rake < 15.0 || rake > 40.0 {
                return Err("rake_angle_deg must be between 15° and 40°".to_string());
            }
        }
        if let Some(fn_hz) = self.fn_target_hz {
            if fn_hz < 0.8 || fn_hz > 4.0 {
                return Err("fn_target_hz must be between 0.8 and 4.0 Hz".to_string());
            }
        }
        if let Some(zeta) = self.zeta_target {
            if zeta < 0.1 || zeta > 0.8 {
                return Err("zeta_target must be between 0.1 and 0.8".to_string());
            }
        }
        Ok(())
    }

    /// Front/rear load distribution per SAE J1299 §4.1.
    /// Based on typical wheelbase CG position.
    /// EV motos shift weight rearward due to battery placement.
    fn axle_load_fraction(&self) -> f64 {
        if let Some(front_pct) = self.front_weight_distribution_pct {
            return match self.axle {
                MotoAxle::Front => front_pct / 100.0,
                MotoAxle::Rear  => 1.0 - (front_pct / 100.0),
            };
        }
        let is_electric = matches!(self.moto_class, MotoClass::ElectricMoto);
        match (&self.axle, is_electric) {
            (MotoAxle::Front, false) => 0.48, // ICE: slightly front-heavy with engine
            (MotoAxle::Rear,  false) => 0.52,
            (MotoAxle::Front, true)  => 0.44, // EV: battery rearward shifts load back
            (MotoAxle::Rear,  true)  => 0.56,
        }
    }

    /// Unsprung mass fraction per SAE J1299 §4.2.
    /// Forks carry heavier unsprung (wheel + brake disc + caliper + axle + fork lowers).
    /// Rear swingarm shares mass between sprung and unsprung more favourably.
    fn unsprung_fraction(&self) -> f64 {
        match self.susp_type {
            MotoSuspType::UsdFork        => 0.17, // lighter lowers
            MotoSuspType::TelescopicFork => 0.21, // heavier conventional lowers
            MotoSuspType::Telelever      => 0.14, // BMW: very low unsprung front
            MotoSuspType::Monoshock      => 0.16, // rear: swingarm is partially sprung
            MotoSuspType::DualShock      => 0.18,
            MotoSuspType::Paralever      => 0.15, // BMW: anti-squat, optimised rear
        }
    }

    /// Default rake angle [degrees] per SAE J1299 class.
    fn default_rake_deg(&self) -> f64 {
        match self.moto_class {
            MotoClass::Scooter       => 27.0,
            MotoClass::Commuter      => 26.0,
            MotoClass::Middleweight  => 25.0,
            MotoClass::Supersport    => 23.0,
            MotoClass::Heavyweight   => 26.0,
            MotoClass::Adventure     => 27.5,
            MotoClass::Offroad       => 28.0,
            MotoClass::ElectricMoto  => 25.0,
        }
    }

    /// Target ride natural frequency [Hz] per SAE J1299.
    /// Motorcycles run higher fn than cars due to lower ms and
    /// the need for quick response to road inputs.
    fn default_fn_hz(&self) -> f64 {
        match (&self.axle, &self.moto_class) {
            // Front: higher fn for steering stability (SAE J1299 §5.2)
            (MotoAxle::Front, MotoClass::Offroad)     => 3.0, // long travel, soft spring
            (MotoAxle::Front, MotoClass::Adventure)   => 2.2,
            (MotoAxle::Front, MotoClass::Supersport)  => 2.5,
            (MotoAxle::Front, MotoClass::ElectricMoto)=> 2.0,
            (MotoAxle::Front, _)                      => 2.2,
            // Rear: slightly lower for ride comfort (SAE J1299 §5.3)
            (MotoAxle::Rear, MotoClass::Offroad)      => 2.8,
            (MotoAxle::Rear, MotoClass::Adventure)    => 2.0,
            (MotoAxle::Rear, MotoClass::Supersport)   => 2.8,
            (MotoAxle::Rear, MotoClass::ElectricMoto) => 1.9,
            (MotoAxle::Rear, _)                       => 2.2,
        }
    }

    /// Target damping ratio per SAE J1299.
    /// Motorcycles run slightly higher ζ than cars for single-track stability.
    fn default_zeta(&self) -> f64 {
        match (&self.moto_class, &self.axle) {
            (MotoClass::Offroad,    _)              => 0.25, // plush off-road
            (MotoClass::Supersport, MotoAxle::Rear) => 0.38, // firm rear for drive
            (MotoClass::Supersport, _)              => 0.35,
            (MotoClass::Adventure,  _)              => 0.28,
            (MotoClass::ElectricMoto, _)            => 0.28, // battery isolation
            _                                       => 0.30,
        }
    }

    /// Tyre radial stiffness [N/m] per SAE J2358.
    /// Motorcycle tyres are narrower but operate at higher pressure.
    /// Front tyre slightly softer than rear (smaller section width).
    fn tyre_stiffness(&self) -> f64 {
        let base = match (&self.axle, &self.moto_class) {
            (MotoAxle::Front, MotoClass::Scooter)      => 90_000.0,
            (MotoAxle::Front, MotoClass::Offroad)      => 70_000.0,  // knobbly, soft
            (MotoAxle::Front, MotoClass::Supersport)   => 140_000.0,
            (MotoAxle::Front, MotoClass::Adventure)    => 110_000.0,
            (MotoAxle::Front, MotoClass::ElectricMoto) => 145_000.0, // LRR compound
            (MotoAxle::Front, _)                       => 120_000.0,
            (MotoAxle::Rear,  MotoClass::Scooter)      => 100_000.0,
            (MotoAxle::Rear,  MotoClass::Offroad)      => 75_000.0,
            (MotoAxle::Rear,  MotoClass::Supersport)   => 160_000.0,
            (MotoAxle::Rear,  MotoClass::Adventure)    => 125_000.0,
            (MotoAxle::Rear,  MotoClass::ElectricMoto) => 165_000.0, // heavier + LRR
            (MotoAxle::Rear,  _)                       => 135_000.0,
        };
        base
    }
}

/// Derive SAE J1299-grounded suspension parameters from motorcycle config.
fn derive_moto_suspension_params(cfg: &MotoConfig) -> DerivedParams {
    use std::f64::consts::PI;

    let load_frac  = cfg.axle_load_fraction();
    let u_frac     = cfg.unsprung_fraction();

    // Total corner mass = (dry_mass + rider_mass) * axle_load_fraction
    // SAE J1299 §3.1: rider mass is included in sprung mass
    let total_mass  = cfg.dry_mass_kg + cfg.rider_mass_kg;
    let axle_mass   = total_mass * load_frac;
    let ms          = axle_mass * (1.0 - u_frac);
    let mu          = axle_mass * u_frac;

    // Rake angle effect on effective spring rate (SAE J1299 §4.3)
    // k_eff = k_spring × cos²(rake_rad)
    // We derive k_eff from fn_target, then back-calculate k_spring
    let rake_deg  = cfg.rake_angle_deg.unwrap_or_else(|| cfg.default_rake_deg());
    let rake_rad  = rake_deg * PI / 180.0;
    let cos2_rake = rake_rad.cos().powi(2);

    let fn_hz   = cfg.fn_target_hz.unwrap_or_else(|| cfg.default_fn_hz());
    let omega_n = 2.0_f64 * PI * fn_hz;

    // k_eff = ms × ωn²  →  k_spring = k_eff / cos²(rake)  (front only)
    let k_eff    = ms * omega_n * omega_n;
    let k_spring = match cfg.axle {
        MotoAxle::Front => k_eff / cos2_rake,
        MotoAxle::Rear  => k_eff, // rake does not apply to rear swingarm
    };

    // Damping from target zeta (applied to k_eff, not k_spring)
    let zeta_t = cfg.zeta_target.unwrap_or_else(|| cfg.default_zeta());
    let c      = 2.0_f64 * zeta_t * (k_eff * ms).sqrt();

    let kt = cfg.tyre_stiffness();

    // Characterisation
    let zeta_actual  = c / (2.0_f64 * (k_eff * ms).sqrt());
    let fn_sprung    = (k_eff / ms).sqrt() / (2.0_f64 * PI);
    let fn_unsprung  = ((k_eff + kt) / mu).sqrt() / (2.0_f64 * PI);

    // SAE notes
    let mut notes = Vec::new();
    notes.push(format!(
        "SAE J1299: Motorcycle mode — {:?} class, {:?} axle",
        cfg.moto_class, cfg.axle
    ));
    notes.push(format!(
        "SAE J1299 §3.1: Rider mass {:.0} kg included in sprung mass",
        cfg.rider_mass_kg
    ));
    notes.push(format!(
        "SAE J1299 §4.1: Axle load fraction {:.0}% ({:?})",
        load_frac * 100.0, cfg.axle
    ));
    notes.push(format!(
        "SAE J1299 §4.2: Unsprung fraction {:.0}% ({:?})",
        u_frac * 100.0, cfg.susp_type
    ));
    if matches!(cfg.axle, MotoAxle::Front) {
        notes.push(format!(
            "SAE J1299 §4.3: Rake {:.1}° → cos²(rake) = {:.3} → k_spring = {:.0} N/m, k_eff = {:.0} N/m",
            rake_deg, cos2_rake, k_spring, k_eff
        ));
    }
    notes.push(format!(
        "Ride fn = {:.2} Hz (SAE J1299 range 1.5–3.0 Hz)",
        fn_sprung
    ));
    notes.push(format!(
        "Wheel-hop fn = {:.1} Hz (SAE J1299 target 12–20 Hz for motorcycles)",
        fn_unsprung
    ));
    notes.push(format!(
        "Damping ratio ζ = {:.3} (SAE J1299 range 0.20–0.40)",
        zeta_actual
    ));
    notes.push(format!(
        "Tyre kt = {:.0} N/m (SAE J2358{})",
        kt,
        if matches!(cfg.moto_class, MotoClass::ElectricMoto) {
            " — LRR compound, higher stiffness"
        } else { "" }
    ));

    // SAE compliance warnings
    if fn_sprung < 1.2 || fn_sprung > 4.0 {
        notes.push(format!(
            "⚠ WARNING: fn_sprung {:.2} Hz outside SAE J1299 recommended range [1.2, 4.0] Hz",
            fn_sprung
        ));
    }
    if zeta_actual < 0.15 || zeta_actual > 0.55 {
        notes.push(format!(
            "⚠ WARNING: ζ = {:.3} outside SAE J1299 range [0.15, 0.55]",
            zeta_actual
        ));
    }

    // Return using k_spring as the physical spring rate
    // (the simulation will use this directly; the effective stiffness
    //  at the wheel is handled by the quarter-car geometry)
    DerivedParams {
        ms, mu,
        k:  k_spring,
        c,
        kt,
        zeta: zeta_actual,
        fn_sprung_hz:   fn_sprung,
        fn_unsprung_hz: fn_unsprung,
        corner_load_fraction: load_frac,
        sae_notes: notes,
    }
}

/// POST /moto/params
///
/// Accepts a MotoConfig and returns SAE J1299-derived suspension parameters.
/// The returned ms, mu, k, c, kt can be passed directly to POST /simulate.
///
/// Example request (BMW GS-style adventure, front fork):
/// {
///   "moto_class": "Adventure",
///   "axle": "Front",
///   "susp_type": "UsdFork",
///   "dry_mass_kg": 249,
///   "rider_mass_kg": 80,
///   "rake_angle_deg": 27.5
/// }
#[post("/moto/params", format = "json", data = "<input>")]
fn moto_params_api(input: Json<MotoConfig>) -> ApiResult<DerivedParams> {
    input.validate().map_err(|e| bad_request(&e))?;
    Ok(Json(derive_moto_suspension_params(&input)))
}

// ═══════════════════════════════════════════════════════════
// SECTION 7.5 — /speed_sweep and /frf_compare
// ═══════════════════════════════════════════════════════════

#[derive(Deserialize)]
#[serde(crate = "rocket::serde")]
struct SpeedSweepInput {
    ms: f64,
    mu: f64,
    k: f64,
    c: f64,
    kt: f64,
    roughness_coefficient: f64,
    speeds_mps: Vec<f64>,
    travel_limit_mm: f64,
}

#[derive(Serialize, Deserialize)]
#[serde(crate = "rocket::serde")]
struct SpeedSweepPoint {
    speed_mps: f64,
    iso2631_mean: f64,
    iso2631_std: f64,
    rms_body_acc_mean: f64,
    rms_tire_force_mean: f64,
}

#[post("/speed_sweep", format = "json", data = "<input>")]
async fn speed_sweep_api(input: Json<SpeedSweepInput>) -> ApiResult<Vec<SpeedSweepPoint>> {
    let inp = input.into_inner();
    let ms = inp.ms;
    let mu = inp.mu;
    let k = inp.k;
    let c = inp.c;
    let kt = inp.kt;
    let travel_limit_m = inp.travel_limit_mm / 1000.0;
    
    let mut results = Vec::new();
    for &speed in &inp.speeds_mps {
        let mut iso_vals = Vec::new();
        let mut rms_acc = Vec::new();
        let mut rms_tire = Vec::new();
        
        for s in 0..30 {
            let profile = RoadProfile::Iso8608 {
                roughness_coefficient: inp.roughness_coefficient,
                vehicle_speed_mps: speed,
                seed: s as u64,
            };
            let r = run_simulation(ms, mu, k, c, kt, travel_limit_m, &profile);
            iso_vals.push(r.iso2631_weighted_rms);
            rms_acc.push(r.rms_body_acc);
            rms_tire.push(r.rms_tire_force);
        }
        
        let iso_m = iso_vals.iter().sum::<f64>() / 30.0;
        let iso_v = iso_vals.iter().map(|v| (v - iso_m).powi(2)).sum::<f64>() / 30.0;
        
        let rms_m = rms_acc.iter().sum::<f64>() / 30.0;
        let tire_m = rms_tire.iter().sum::<f64>() / 30.0;
        
        results.push(SpeedSweepPoint {
            speed_mps: speed,
            iso2631_mean: iso_m,
            iso2631_std: iso_v.sqrt(),
            rms_body_acc_mean: rms_m,
            rms_tire_force_mean: tire_m,
        });
    }
    Ok(Json(results))
}

#[derive(Deserialize)]
#[serde(crate = "rocket::serde")]
struct FrfCompareInput {
    car: FrfInput,
    bike: FrfInput,
    freq_range_hz: Vec<f64>,
}

#[derive(Serialize, Deserialize)]
#[serde(crate = "rocket::serde")]
struct FrfCompareOutput {
    car: Vec<FrfPoint>,
    bike: Vec<FrfPoint>,
}

#[post("/frf_compare", format = "json", data = "<input>")]
async fn frf_compare_api(input: Json<FrfCompareInput>) -> ApiResult<FrfCompareOutput> {
    let inp = input.into_inner();
    
    let compute = |config: FrfInput| -> Result<Vec<FrfPoint>, Custom<Json<ApiError>>> {
        let ms = config.ms.ok_or_else(|| bad_request("ms is required"))?;
        let mu = config.mu.ok_or_else(|| bad_request("mu is required"))?;
        let k = config.k.ok_or_else(|| bad_request("k is required"))?;
        let c = config.c.ok_or_else(|| bad_request("c is required"))?;
        let kt = config.kt.ok_or_else(|| bad_request("kt is required"))?;
        
        let points = compute_frf(ms, mu, k, c, kt, &inp.freq_range_hz, 0.01);
        Ok(points.into_iter().map(|p| FrfPoint {
            freq_hz: p.freq_hz,
            body_acc_transmissibility: p.body_acc_transmissibility,
            tire_force_transmissibility: p.tire_force_transmissibility,
        }).collect())
    };
    
    let car_res = compute(inp.car)?;
    let bike_res = compute(inp.bike)?;
    
    Ok(Json(FrfCompareOutput {
        car: car_res,
        bike: bike_res,
    }))
}

// ═══════════════════════════════════════════════════════════
// SECTION 8 — Index + main
// ═══════════════════════════════════════════════════════════

#[get("/")]
fn index() -> &'static str {
    "Suspension Analysis API\n\
     POST /simulate        — run simulation\n\
     GET  /history         — past runs\n\
     POST /frf             — frequency response function\n\
     POST /sweep           — parameter sweep + Pareto front\n\
     POST /vehicle/params  — derive SAE-grounded suspension params from vehicle config\n\
     POST /moto/params     — derive SAE J1299 suspension params from motorcycle config"
}

// Handles browser CORS preflight OPTIONS requests
#[rocket::options("/<_..>")]
fn options() -> &'static str { "" }

#[rocket::main]
async fn main() -> Result<(), rocket::Error> {
    dotenv().ok();

    let database_url = env::var("DATABASE_URL")
        .unwrap_or_else(|_| {
            eprintln!("ERROR: DATABASE_URL env var not set");
            std::process::exit(1);
        });

    let pool = PgPoolOptions::new()
        .max_connections(5)
        .connect(&database_url)
        .await
        .unwrap_or_else(|e| {
            eprintln!("ERROR: Failed to connect to Postgres: {e}");
            std::process::exit(1);
        });

    println!("Connected to PostgreSQL.");

    rocket::build()
        .attach(Cors)
        .manage(pool)
        .mount("/", routes![index, options, simulate_api, history, frf_api, sweep_api, vehicle_params_api, moto_params_api, validation_schema_api, speed_sweep_api, frf_compare_api])
        .launch()
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rocket::local::blocking::Client;
    use rocket::http::{ContentType, Status};

    fn rocket_instance() -> rocket::Rocket<rocket::Build> {
        rocket::build().mount("/", routes![speed_sweep_api, frf_compare_api])
    }

    #[test]
    fn test_speed_sweep_endpoint() {
        let client = Client::tracked(rocket_instance()).expect("valid rocket instance");
        let payload = r#"{
            "ms": 290.0,
            "mu": 40.0,
            "k": 22000.0,
            "c": 1500.0,
            "kt": 190000.0,
            "roughness_coefficient": 0.000001,
            "speeds_mps": [10.0, 20.0],
            "travel_limit_mm": 120.0
        }"#;
        let response = client.post("/speed_sweep")
            .header(ContentType::JSON)
            .body(payload)
            .dispatch();

        assert_eq!(response.status(), Status::Ok);
        let results: Vec<SpeedSweepPoint> = response.into_json().unwrap();
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn test_frf_compare_endpoint() {
        let client = Client::tracked(rocket_instance()).expect("valid rocket instance");
        let payload = r#"{
            "car": {
                "ms": 300.0, "mu": 40.0, "k": 20000.0, "c": 1500.0, "kt": 200000.0, "travel_limit_mm": 120.0
            },
            "bike": {
                "ms": 150.0, "mu": 20.0, "k": 10000.0, "c": 750.0, "kt": 100000.0, "travel_limit_mm": 120.0
            },
            "freq_range_hz": [1.0, 10.0]
        }"#;
        let response = client.post("/frf_compare")
            .header(ContentType::JSON)
            .body(payload)
            .dispatch();

        assert_eq!(response.status(), Status::Ok);
        let results: FrfCompareOutput = response.into_json().unwrap();
        assert_eq!(results.car.len(), 2);
        assert_eq!(results.bike.len(), 2);
    }
}